### PR TITLE
issues/18: support for sch:extends without @href

### PR DESCRIPTION
**Pull request by cmarchand**
Re-creating it, it replaces closed https://github.com/mricaud/xml-utilities/pull/19

### CODE REVIEW

**Comment by cmarchand** [comment]
As you do not define `<xsl:mode name="xut:get-xmldependency-tree"/>` with a behavior for `on-no-match`, I prefer defining a template to avoid any output for these cases.
But it's up to you, if you prefer, I can remove it.

**Comment by mricaud** [comment]
Actually there are default templates to avoid copiying anything at line 347:

```xml
<xsl:template match="*" mode="xut:get-xml-dependency-tree" priority="-2">
  <xsl:apply-templates mode="#current"/>
</xsl:template>

<xsl:template match="text()" mode="xut:get-xml-dependency-tree" priority="-1"/>

<xsl:template match="/*" mode="xut:get-xml-dependency-tree.specific-attributes-set" priority="-1"/>
```
But yes `<xsl:mode name="xut:get-xml-dependency-tree" on-no-match="shallow-skip"/>` would be better and do the same thing I guess.

Anyway you can delete the extra template, no risk :)

**Comment by cmarchand** [comment]
Done

**Comment by cmarchand** [comment]
To deploy a new release :

1.  update pom to set the desired version
2.  commit, tag, push
3.  mvn -Prelease deploy
4.  update pom to set new snapshot
5.  commit push

**Review by mricaud — APPROVED** [review]

**Pull request merged**
