### PR TITLE
issues/18: support for sch:extends without @href

### PR DESCRIPTION
**Pull request by cmarchand**
Fix proposal for issue #18

### CODE REVIEW

**Comment by mricaud** [comment]
Hi @cmarchand 
I didn't know sch:extends `href `attribute was optional, but it's true it can have a `@rule` attribute instead, as the spec says:

> The extends element allows reference to the contents of other declarations. The extends element shall
either have an href attribute or a rule attribute but not both.

Concerning the implementation in `get-xml-file-static-dependency-tree.xsl`, I think you don't need to match `sch:extends[not(@href)]`, because there is no default copy template: unmatched elements are always ignored.

Could you add and example of `extends `without `href `attribute in the test sample?
(there's no XSPec tests upon those samples but it might be done later)

**Comment by cmarchand** [comment]
I don't know if you are this one' author, but have a look at it : https://bitbucket.org/elsgestion/sie-xf-xdev-flash/src/ce76d757fd58e10cde70ee38e7d8beadf4a487cf/modules/sie-xf-editor/src/main/grammars/efl/infoCommentaire/xf_infoCommentaire.html.sch#lines-349
I'm not very good in schematron, but you'd be the author...

**Comment by cmarchand** [comment]
I've rebased the PR to include your commits in. So I close this PR and I recreate it

**Comment by mricaud** [comment]
Oh that's true, I'm the author of this schematron :) 
I didn't remember that calling abstract patterns _within schematron rules_ also uses sch:extends just like importing external rule from another file (but at top level)

Ok let's look the other PR then !

**Pull request closed without merging**
